power: qcom: For support use both SMB5 and SMBLITE in the same image
If need to use both SMB5 and SMBLITE in the same image, need enable
CONFIG_SUPPORT_BOTH_SMB5_SMBLITE config. Otherwise, will make the following
error log:
drivers/power/supply/qcom/smblite-iio.c:226: multiple definition of `get_ext_channels';
drivers/power/supply/qcom/smb5-iio.o:/drivers/power/supply/qcom/smb5-iio.c:509: first defined here

Change-Id: Ie11baa127197379280d93463779f27046e33880c
Signed-off-by: Hongwei Ren <hongren@codeaurora.org>